main: atzen.Atzen
name: Atzen
version: 1.0
api-version: 1.20
author: morty

commands:
  atzen:
    description: Control the drop behavior
    usage: /atzen randomizeAmount [true|false]
    permission: atzen.toggle
    permission-message: You do not have permission to use this command.
