name: RandomMobBattle
version: 1.0
main: randommobbattle.RandomMobBattle
api-version: 1.16
description: Drops random items on block break and shows mob kill stats with spawn eggs.

commands:
  mobstats:
    description: Zeigt dir deine Mob-Kills an
    usage: /mobstats
